function createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, X7, Y6, X8, Y7, X9, X10, Y8, X11, Y9, X12, X13, Y10, X14, Y11, X15, X16, Y12, X17, Y13, X18, X19, Y14, X20, Y15, X21, X22, Y16, X23, Y17, X24, X25, X26, Y18, X27, X28, X29, X30, X31, X32, X33, X34, X35, X36, X37, X38, X39, X40, X41, X42, X43, X44, X45, X46, YMatrix1, X47, YMatrix2, X48, YMatrix3, X49, YMatrix4)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3,X4,Y4,X5,Y5,X6,X7,Y6,X8,Y7,X9,X10,Y8,X11,Y9,X12,X13,Y10,X14,Y11,X15,X16,Y12,X17,Y13,X18,X19,Y14,X20,Y15,X21,X22,Y16,X23,Y17,X24,X25,X26,Y18,X27,X28,X29,X30,X31,X32,X33,X34,X35,X36,X37,X38,X39,X40,X41,X42,X43,X44,X45,X46,YMATRIX1,X47,YMATRIX2,X48,YMATRIX3,X49,YMATRIX4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  X7:  vector of x data
%  Y6:  vector of y data
%  X8:  vector of x data
%  Y7:  vector of y data
%  X9:  vector of x data
%  X10:  vector of x data
%  Y8:  vector of y data
%  X11:  vector of x data
%  Y9:  vector of y data
%  X12:  vector of x data
%  X13:  vector of x data
%  Y10:  vector of y data
%  X14:  vector of x data
%  Y11:  vector of y data
%  X15:  vector of x data
%  X16:  vector of x data
%  Y12:  vector of y data
%  X17:  vector of x data
%  Y13:  vector of y data
%  X18:  vector of x data
%  X19:  vector of x data
%  Y14:  vector of y data
%  X20:  vector of x data
%  Y15:  vector of y data
%  X21:  vector of x data
%  X22:  vector of x data
%  Y16:  vector of y data
%  X23:  vector of x data
%  Y17:  vector of y data
%  X24:  vector of x data
%  X25:  vector of x data
%  X26:  vector of x data
%  Y18:  vector of y data
%  X27:  vector of x data
%  X28:  vector of x data
%  X29:  vector of x data
%  X30:  vector of x data
%  X31:  vector of x data
%  X32:  vector of x data
%  X33:  vector of x data
%  X34:  vector of x data
%  X35:  vector of x data
%  X36:  vector of x data
%  X37:  vector of x data
%  X38:  vector of x data
%  X39:  vector of x data
%  X40:  vector of x data
%  X41:  vector of x data
%  X42:  vector of x data
%  X43:  vector of x data
%  X44:  vector of x data
%  X45:  vector of x data
%  X46:  vector of x data
%  YMATRIX1:  matrix of y data
%  X47:  vector of x data
%  YMATRIX2:  matrix of y data
%  X48:  vector of x data
%  YMATRIX3:  matrix of y data
%  X49:  vector of x data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 20-May-2010 19:23:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.099250936329588 0.107329842931937 0.866266305049722 0.817670157068065]);
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create plot
plot(X2,Y2);

% Create plot
plot(X3,Y3,'LineWidth',2);

% Create plot
plot(X4,Y4);

% Create plot
plot(X5,Y5);

% Create plot
plot(X6,Y3,'LineWidth',2);

% Create plot
plot(X7,Y6);

% Create plot
plot(X8,Y7);

% Create plot
plot(X9,Y3,'LineWidth',2);

% Create plot
plot(X10,Y8);

% Create plot
plot(X11,Y9);

% Create plot
plot(X12,Y3,'LineWidth',2);

% Create plot
plot(X13,Y10);

% Create plot
plot(X14,Y11);

% Create plot
plot(X15,Y3,'LineWidth',2);

% Create plot
plot(X16,Y12);

% Create plot
plot(X17,Y13);

% Create plot
plot(X18,Y3,'LineWidth',2);

% Create plot
plot(X19,Y14);

% Create plot
plot(X20,Y15);

% Create plot
plot(X21,Y3,'LineWidth',2);

% Create plot
plot(X22,Y16);

% Create plot
plot(X23,Y17);

% Create plot
plot(X24,Y3,'LineWidth',2);

% Create plot
plot(X25,Y3,'Color',[0 0 1]);

% Create plot
plot(X26,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X27,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X28,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X29,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X30,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X31,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X32,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X33,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X34,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X35,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X36,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X37,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X38,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X39,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X40,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X41,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X42,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X43,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X44,Y18,'Marker','o','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X45,Y18,'Marker','o','LineStyle','none','Color',[0 1 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X46,YMatrix1,'LineWidth',2);
set(plot1(1),'Color',[0 1 0]);
set(plot1(2),'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(X47,YMatrix2,'LineWidth',2);
set(plot2(1),'Color',[0 1 0]);
set(plot2(2),'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot3 = plot(X48,YMatrix3,'LineWidth',2);
set(plot3(1),'Color',[0 1 0]);
set(plot3(2),'Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot4 = plot(X49,YMatrix4,'LineWidth',2,'Parent',axes1);
set(plot4(1),'Color',[0 1 0]);
set(plot4(2),'Color',[0 0 0]);
set(plot4(3),'Color',[0 1 0]);
set(plot4(4),'Color',[0 0 0]);
set(plot4(5),'Color',[0 1 0]);
set(plot4(6),'Color',[0 0 0]);
set(plot4(7),'Color',[0 1 0]);
set(plot4(8),'Color',[0 0 0]);
set(plot4(9),'Color',[0 1 0]);
set(plot4(10),'Color',[0 0 0]);
set(plot4(11),'Color',[0 1 0]);
set(plot4(12),'Color',[0 0 0]);
set(plot4(13),'Color',[0 1 0]);
set(plot4(14),'Color',[0 0 0]);

% Create xlabel
xlabel({'t'});

% Create ylabel
ylabel({'x'});

% Create line
annotation(figure1,'line',[0.952111207341027 0.952976798972537],...
    [0.83990098824291 0.508498200038124],'LineWidth',3);

% Create textarrow
annotation(figure1,'textarrow',[0.243828443625839 0.276813957213589],...
    [0.5611602357985 0.370240782431163],'TextEdgeColor','none',...
    'String',{'\alpha_1'});

% Create textarrow
annotation(figure1,'textarrow',[0.158860676226812 0.20306014424409],...
    [0.51118703108253 0.388801460762996],'TextEdgeColor','none',...
    'String',{'\alpha_2'});

% Create line
annotation(figure1,'line',[0.107507299720482 0.106605193453078],...
    [0.293688271636676 0.112611371971034],'LineWidth',3);

% Create textarrow
annotation(figure1,'textarrow',[0.792971977371398 0.956613603473227],...
    [0.818916765386134 0.716340187284933],'TextEdgeColor','none',...
    'String',{'X_2'});

% Create textarrow
annotation(figure1,'textarrow',[0.344563469277996 0.310382008225791],...
    [0.668630150958792 0.48655432185114],'TextEdgeColor','none',...
    'String',{'X^{\alpha_2}_1'});

% Create textarrow
annotation(figure1,'textarrow',[0.65293250888041 0.604920405209841],...
    [0.348116573588312 0.370614035087719],'TextEdgeColor','none',...
    'String',{'\alpha_1'});

% Create textarrow
annotation(figure1,'textarrow',[0.811853703460071 0.722141823444284],...
    [0.350746742257573 0.471491228070175],'TextEdgeColor','none',...
    'String',{'X^{\alpha_1}_1'});

% Create textarrow
annotation(figure1,'textarrow',[0.194640338504937 0.107091172214182],...
    [0.258162303664921 0.256578947368421],'TextEdgeColor','none',...
    'String',{'X_0'});

% Create textarrow
annotation(figure1,'textarrow',[0.429498750164452 0.283022198116791],...
    [0.208717634117448 0.330886235472552],'TextEdgeColor','none',...
    'String',{'\alpha_2'});

