function createfigure(X1, Y1, X2, Y2, X3, Y3, plot_x1, plot_y1, plot_x2, plot_y2, X4, X5, t1_exact1, H1, X6, X7, YMatrix1, X8, Y4, X9, Y5, X10, Y6, X11, Y7, X12, Y8, X13, Y9, X14, Y10, X15, Y11, X16, Y12, X17, Y13)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3,PLOT_X1,PLOT_Y1,PLOT_X2,PLOT_Y2,X4,X5,T1_EXACT1,H1,X6,X7,YMATRIX1,X8,Y4,X9,Y5,X10,Y6,X11,Y7,X12,Y8,X13,Y9,X14,Y10,X15,Y11,X16,Y12,X17,Y13)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  PLOT_X1:  vector of x data
%  PLOT_Y1:  vector of y data
%  PLOT_X2:  vector of x data
%  PLOT_Y2:  vector of y data
%  X4:  vector of x data
%  X5:  vector of x data
%  T1_EXACT1:  vector of x data
%  H1:  vector of y data
%  X6:  vector of x data
%  X7:  vector of x data
%  YMATRIX1:  matrix of y data
%  X8:  vector of x data
%  Y4:  vector of y data
%  X9:  vector of x data
%  Y5:  vector of y data
%  X10:  vector of x data
%  Y6:  vector of y data
%  X11:  vector of x data
%  Y7:  vector of y data
%  X12:  vector of x data
%  Y8:  vector of y data
%  X13:  vector of x data
%  Y9:  vector of y data
%  X14:  vector of x data
%  Y10:  vector of y data
%  X15:  vector of x data
%  Y11:  vector of y data
%  X16:  vector of x data
%  Y12:  vector of y data
%  X17:  vector of x data
%  Y13:  vector of y data

%  Auto-generated by MATLAB on 20-May-2010 17:43:27

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0895588235294113 0.100314769975787 0.883097426470589 0.815]);
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create plot
plot(X2,Y2);

% Create plot
plot(X3,Y3,'LineWidth',2);

% Create plot
plot(plot_x1,plot_y1,'DisplayName','plot_y1 vs. plot_x1');

% Create plot
plot(plot_x2,plot_y2,'DisplayName','plot_y2 vs. plot_x2');

% Create plot
plot(X4,Y3,'LineWidth',2);

% Create plot
plot(X5,Y3,'Color',[0 0 1]);

% Create plot
plot(t1_exact1,H1,'Marker','o','LineStyle','none','Color',[1 0 0],...
    'DisplayName','H vs. t1_exact');

% Create plot
plot(X6,H1,'Marker','o','LineStyle','none','Color',[0 1 0],...
    'DisplayName','H');

% Create multiple lines using matrix input to plot
plot1 = plot(X7,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'Color',[0 1 0]);
set(plot1(2),'Color',[0 0 0]);
set(plot1(3),'Color',[1 1 0]);

% Create plot
plot(X8,Y4,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X9,Y5,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X10,Y6,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X11,Y7,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X12,Y8,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X13,Y9,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X14,Y10,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X15,Y11,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X16,Y12,'LineWidth',2,'Color',[1 1 0]);

% Create plot
plot(X17,Y13,'LineWidth',2,'Color',[1 1 0]);

% Create xlabel
xlabel({'t'});

% Create ylabel
ylabel({'x'});

% Create textarrow
annotation(figure1,'textarrow',[0.167857142857143 0.183928571428571],...
    [0.744238095238095 0.578571428571429],'TextEdgeColor','none','String',{'H'});

% Create textarrow
annotation(figure1,'textarrow',[0.264285714285714 0.305357142857143],...
    [0.749 0.580952380952381],'TextEdgeColor','none','String',{'X^1_1\cap H'});

% Create textarrow
annotation(figure1,'textarrow',[0.737976782752902 0.946520353618421],...
    [0.836772397094431 0.771186440677966],'TextEdgeColor','none',...
    'String',{'X_2[t_1]'});

% Create line
annotation(figure1,'line',[0.95201614064643 0.953525495897306],...
    [0.854189795975107 0.688242871019533],'LineWidth',3);

% Create textarrow
annotation(figure1,'textarrow',[0.26865671641791 0.0946837308114035],...
    [0.175755447941889 0.194915254237288],'TextEdgeColor','none',...
    'String',{'X_0'});

% Create textarrow
annotation(figure1,'textarrow',[0.508928571428571 0.623209635416667],...
    [0.746619047619048 0.565548253199585],'TextEdgeColor','none',...
    'String',{'X^2_1\cap H'});

% Create textarrow
annotation(figure1,'textarrow',[0.728571428571429 0.61443672548928],...
    [0.484714285714286 0.475589149272505],'TextEdgeColor','none',...
    'String',{'Disturbance2'});

% Create line
annotation(figure1,'line',[0.0908203125 0.0928217252256668],...
    [0.335351089588378 0.102321962327327],'LineWidth',3);

