function createfigure(X1, YMatrix1, X2, YMatrix2, VertexNormals1, YData1, XData1, Vertices1, Faces1, VertexNormals2, YData2, XData2, Vertices2, Faces2, VertexNormals3, YData3, XData3, Vertices3, Faces3, VertexNormals4, YData4, XData4, Vertices4, Faces4, X3, Y1, X4, X5, X6)
%CREATEFIGURE(X1,YMATRIX1,X2,YMATRIX2,VERTEXNORMALS1,YDATA1,XDATA1,VERTICES1,FACES1,VERTEXNORMALS2,YDATA2,XDATA2,VERTICES2,FACES2,VERTEXNORMALS3,YDATA3,XDATA3,VERTICES3,FACES3,VERTEXNORMALS4,YDATA4,XDATA4,VERTICES4,FACES4,X3,Y1,X4,X5,X6)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  VERTEXNORMALS2:  patch vertexnormals
%  YDATA2:  patch ydata
%  XDATA2:  patch xdata
%  VERTICES2:  patch vertices
%  FACES2:  patch faces
%  VERTEXNORMALS3:  patch vertexnormals
%  YDATA3:  patch ydata
%  XDATA3:  patch xdata
%  VERTICES3:  patch vertices
%  FACES3:  patch faces
%  VERTEXNORMALS4:  patch vertexnormals
%  YDATA4:  patch ydata
%  XDATA4:  patch xdata
%  VERTICES4:  patch vertices
%  FACES4:  patch faces
%  X3:  vector of x data
%  Y1:  vector of y data
%  X4:  vector of x data
%  X5:  vector of x data
%  X6:  vector of x data

%  Auto-generated by MATLAB on 23-May-2010 18:16:34

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.13 0.11 0.4227 0.815]);
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'Parent',axes1);

% Create multiple lines using matrix input to plot
plot(X2,YMatrix2);

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor',[1 1 0]);

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals2,'YData',YData2,...
    'XData',XData2,...
    'Vertices',Vertices2,...
    'Faces',Faces2,...
    'FaceColor',[1 1 0]);

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals3,'YData',YData3,...
    'XData',XData3,...
    'Vertices',Vertices3,...
    'Faces',Faces3,...
    'FaceColor',[1 1 0]);

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals4,'YData',YData4,...
    'XData',XData4,...
    'Vertices',Vertices4,...
    'Faces',Faces4,...
    'FaceColor',[1 1 0]);

% Create plot
plot(X3,Y1,'LineWidth',3,'Color',[1 0 0]);

% Create plot
plot(X4,Y1,'LineWidth',3,'Color',[1 0 0]);

% Create plot
plot(X5,Y1,'LineWidth',3,'Color',[1 0 0]);

% Create plot
plot(X6,Y1,'LineWidth',3,'Color',[1 0 0]);

% Create xlabel
xlabel({'t'});

% Create ylabel
ylabel({'x'});

% Create textarrow
annotation(figure1,'textarrow',[0.1726 0.1962],[0.6657 0.4758],...
    'TextEdgeColor','none',...
    'String',{'X_1\cap H'});

% Create line
annotation(figure1,'line',[0.1323 0.1323],[0.1908 0.3478],'LineWidth',2);

% Create textarrow
annotation(figure1,'textarrow',[0.2197 0.1334],[0.1947 0.2585],...
    'TextEdgeColor','none',...
    'String',{'X_0'});

% Create textarrow
annotation(figure1,'textarrow',[0.4821 0.4148],[0.2874 0.4783],...
    'TextEdgeColor','none',...
    'String',{'H'});

