function createfigure(X1, Y1, X2, X3, YMatrix1, X4, Y2)
%CREATEFIGURE(X1,Y1,X2,X3,YMATRIX1,X4,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data
%  YMATRIX1:  matrix of y data
%  X4:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 24-May-2010 18:47:04

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1,'PlotBoxAspectRatio',[520.8 410.8 410.8],...
    'DataAspectRatio',[1 1 1]);
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X2,X2,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix1,'Marker','o','LineStyle','none','Parent',axes1);
set(plot1(3),'Color',[0 0 0]);

% Create plot
plot(X4,Y2,'Color',[0 0 1]);

% Create arrow
annotation(figure1,'arrow',[0.6324 0.6324],[0.5198 0.6401],'LineWidth',2);

% Create arrow
annotation(figure1,'arrow',[0.5245 0.6295],[0.5136 0.5139]);

% Create textbox
annotation(figure1,'textbox',[0.5098 0.534 0.0915 0.06226],...
    'String',{'H(c,\gamma)'},...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create textarrow
annotation(figure1,'textarrow',[0.4085 0.6291],[0.8025 0.7451],...
    'TextEdgeColor','none',...
    'String',{'E(q_h,A^{-1})'});

% Create textbox
annotation(figure1,'textbox',[0.5788 0.5821 0.03719 0.05837],...
    'String',{'q_h'},...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create line
annotation(figure1,'line',[0.6307 0.6307],[0.429 0.1946]);

% Create textarrow
annotation(figure1,'textarrow',[0.7794 0.6324],[0.4017 0.3424],...
    'TextEdgeColor','none',...
    'String',{'H'});

