function createfigure(X1, Y1, X2, Y2, X3, Y3, Y4, X4, YMatrix1, X5, YMatrix2, X6, Y5, X7, Y6, X8, Y7, X9, Y8, X10, Y9, X11, Y10, X12, X13, YMatrix3, X14, YMatrix4)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3,Y4,X4,YMATRIX1,X5,YMATRIX2,X6,Y5,X7,Y6,X8,Y7,X9,Y8,X10,Y9,X11,Y10,X12,X13,YMATRIX3,X14,YMATRIX4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  X4:  vector of x data
%  YMATRIX1:  matrix of y data
%  X5:  vector of x data
%  YMATRIX2:  matrix of y data
%  X6:  vector of x data
%  Y5:  vector of y data
%  X7:  vector of x data
%  Y6:  vector of y data
%  X8:  vector of x data
%  Y7:  vector of y data
%  X9:  vector of x data
%  Y8:  vector of y data
%  X10:  vector of x data
%  Y9:  vector of y data
%  X11:  vector of x data
%  Y10:  vector of y data
%  X12:  vector of x data
%  X13:  vector of x data
%  YMATRIX3:  matrix of y data
%  X14:  vector of x data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 24-May-2010 18:37:06

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.07053 0.09608 0.8837 0.8471],...
    'PlotBoxAspectRatio',[1.268 1 1],...
    'DataAspectRatio',[1 1 1]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-5 5]);
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X2,Y2,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X3,Y3,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(figure1,Y4,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create multiple lines using matrix input to plot
plot(X4,YMatrix1,'Marker','o','LineStyle','none','Parent',axes1);

% Create multiple lines using matrix input to plot
plot(X5,YMatrix2,'Marker','o','LineStyle','none','Parent',axes1);

% Create plot
plot(X6,Y5,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X7,Y6,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X8,Y7,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X9,Y8,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X10,Y9,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X11,Y10,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X12,Y9,'LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(Y10,Y10,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create multiple lines using matrix input to plot
plot1 = plot(X13,YMatrix3,'LineWidth',2,'Color',[0 0 1]);
set(plot1(2),'LineStyle','--');

% Create multiple lines using matrix input to plot
plot2 = plot(X14,YMatrix4);
set(plot2(1),'Marker','square','LineStyle','none','Color',[0 0 0]);
set(plot2(2),'LineWidth',2,'Color',[0 1 0]);

% Create xlabel
xlabel({'x'});

% Create ylabel
ylabel({'y'});

% Create title
title({'Fixed \tau'});

% Create arrow
annotation(figure1,'arrow',[0.5131 0.6029],[0.8637 0.7392]);

% Create arrow
annotation(figure1,'arrow',[0.5131 0.6912],[0.8676 0.8118]);

% Create arrow
annotation(figure1,'arrow',[0.5147 0.3235],[0.8657 0.7843]);

% Create arrow
annotation(figure1,'arrow',[0.5131 0.4363],[0.8637 0.7176]);

% Create arrow
annotation(figure1,'arrow',[0.7173 0.5768],[0.2941 0.2529]);

% Create textbox
annotation(figure1,'textbox',[0.4542 0.8441 0.1471 0.08431],...
    'String',{'Q(\tau)+\xi_i'},...
    'FontSize',12,...
    'LineStyle','none');

% Create textarrow
annotation(figure1,'textarrow',[0.1536 0.1585],[0.5235 0.4216],...
    'TextEdgeColor','none',...
    'FontSize',12,...
    'String',{'H'});

% Create textbox
annotation(figure1,'textbox',[0.1219 0.8216 0.0856 0.06667],...
    'String',{'R^2'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create textarrow
annotation(figure1,'textarrow',[0.7059 0.5163],[0.7402 0.6294],...
    'TextEdgeColor','none',...
    'String',{'Upper bound'});

% Create textarrow
annotation(figure1,'textarrow',[0.3105 0.4477],[0.1451 0.202],...
    'TextEdgeColor','none',...
    'String',{'Lower bound'});

% Create line
annotation(figure1,'line',[0.3317 0.0768],[0.4108 0.4118],'LineWidth',2);

% Create line
annotation(figure1,'line',[0.6944 0.9363],[0.4108 0.4118],'LineWidth',2);

% Create textbox
annotation(figure1,'textbox',[0.7069 0.2784 0.0709 0.06078],...
    'String',{'Z[\tau]'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create textarrow
annotation(figure1,'textarrow',[0.8105 0.6389],[0.5412 0.4137],...
    'TextEdgeColor','none',...
    'FontSize',12,...
    'String',{'X_1 \cap H'});

